function detJ = detJ_calc(pts, dN_dxi, dN_deta, p, nodes_e,N)
	detJ = dx_dxi_calc(nodes_e(:,1), dN_dxi)...
          *dx_dxi_calc(nodes_e(:,2), dN_deta)...
	      -dx_dxi_calc(nodes_e(:,2), dN_dxi)...
          *dx_dxi_calc(nodes_e(:,1), dN_deta);
end