function detJ = detJ_calc(dN_dxi, dN_deta, nodes_e)
	detJ = dx_dxi_calc(nodes_e(:,1), dN_dxi)...
          *dx_dxi_calc(nodes_e(:,2), dN_deta)...
	      -dx_dxi_calc(nodes_e(:,2), dN_dxi)...
          *dx_dxi_calc(nodes_e(:,1), dN_deta);
end