%returns Guass Quadrature locations and weights
function [pts,W] = guassQuad(nInt)
    switch nInt
        case 1
            pts = [0 0];
            W = 4;
        case 2
            pts = [-sqrt(3)/3 sqrt(3)/3;...
                  sqrt(3)/3 sqrt(3)/3;...
                  -sqrt(3)/3 -sqrt(3)/3;...
                  sqrt(3)/3 -sqrt(3)/3;];
            W = [1;...
                 1;...
                 1;...
                 1;];
        case 3
            pts = [-sqrt(3/5) sqrt(3/5);...
                  0 sqrt(3/5);...
                  sqrt(3/5) sqrt(3/5);...
                  -sqrt(3/5) 0;...
                  0 0;...
                  sqrt(3/5) 0;...
                  -sqrt(3/5) -sqrt(3/5);...
                  0 -sqrt(3/5);...
                  sqrt(3/5) -sqrt(3/5);];
            W = [5/9*5/9;...
                 8/9*5/9;...
                 5/9*5/9;...
                 5/9*8/9;...
                 8/9*8/9;...
                 5/9*8/9;...
                 5/9*5/9;...
                 8/9*5/9;...
                 5/9*5/9;];
    end
end